######
GET http://localhost:3000/user/login



####
GET http://localhost:3000/user/signup


######
POST http://localhost:3000/user/login
Content-Type: application/json

{
	"email" : "avadnikky@gmail.com",
	"password" : "avadnikky"
}




####
POST http://localhost:3000/user/signup
Content-Type: application/json

{
	"email" : "aderinwaleayodeji@gmail.com",
	"password" : "devak1234"
}


####Products URL

GET http://localhost:3000/products






####
POST http://localhost:3000/products
Content-Type: application/json

{
	"name" : "Calm Your Mind Pure Epsom Salt Soak with Ashwagandha",
	"price" : 8500.00,
	"image" : "https://www.drteals.com/wp-content/uploads/2020/03/810021200309_Front.jpg", 
	"category" : "Category: Pure Epsom Salt Soaks",
	"description" : "Helps Ease Aches & Soreness from Muscle Pains",
	"inStock" : true
}

#############
GET http://localhost:3000/products/6744913e75a9bae18510e5c6









##############
GET http://localhost:3000/products?category=Kids





##############
POST http://localhost:3000/cart
Content-Type: application/json

{
	"userId" : "67449d7103499abf248c201d",
	"item" : {
		"productId" : "67449d7103499abf248c201d",
		"quantity": 1
	}
}



###
GET http://localhost:3000/cart/675ac7085e10f1bc6c046247


###

DELETE http://localhost:3000/cart/675ac7085e10f1bc6c046247/67448853f889299dd6e1764e